In [ ]:
import torch

## Linear Algebra

### Scalars
Usually denoted with a lower case letter, such that $x \in \mathbb{R}$.

In [ ]:
a = torch.tensor(3.0)
b = torch.tensor(2.0)
print(a.item())
print(a+b, a*b, a/b, a**b)

3.0
tensor(5.) tensor(6.) tensor(1.5000) tensor(9.)


### Vectors
Usually denoted with a bold lower case letter, such that $\mathbf{x} \in \mathbb{R}^d$, where $\mathbf{x}$ is a $d$-dimensional vector.

In [ ]:
x = torch.arange(3, dtype=torch.float32)
print('Original Vector x: \t\t\t', x)
print('3rd element of x: \t\t\t', x[2])
print('length/dimension of vector: \t\t', len(x))
print('shape of x, defined in torch: \t\t', x.shape)
print('Sum of elements in x: \t\t\t', x.sum())
print()

y = torch.ones(3, dtype=torch.float32)
print('Original Vector y: \t\t\t', y)
print('Inner product between x and y (ver1): \t', torch.dot(x, y))
print('Inner product between x and y (ver2): \t', torch.sum(x*y))

Original Vector x: 			 tensor([0., 1., 2.])
3rd element of x: 			 tensor(2.)
length/dimension of vector: 		 3
shape of x, defined in torch: 		 torch.Size([3])
Sum of elements in x: 			 tensor(3.)

Original Vector y: 			 tensor([1., 1., 1.])
Inner product between x and y (ver1): 	 tensor(3.)
Inner product between x and y (ver2): 	 tensor(3.)


### Matrices
Usually denoted with bold upper case letter, such that $\mathbf{A} \in \mathbb{R}^{m \times n}$, where $\mathbf{A}$ has $m$ rows and $n$ columns.

In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)

print('Original matrix A: ')
print(A)
print()

print('Transpose of matrix A: ')
print(A.T)

Original matrix A: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])

Transpose of matrix A: 
tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])


In [ ]:
print('Shape of A, defined in torch: \t\t', A.shape)
print('Sum of all elements in A: \t\t', A.sum())
print('Sum of each column of A: \t\t', A.sum(dim=0))
print('Shape of A after summing each column: \t', A.sum(dim=0).shape)
print()

print('Sum of each column in A, w/o dimension reduction: \t\t', A.sum(dim=0, keepdims=True))
print('Shape of A after summing each column, w/o dimension reduction: \t', A.sum(dim=0, keepdims=True).shape)
print()

Shape of A, defined in torch: 		 torch.Size([2, 3])
Sum of all elements in A: 		 tensor(15.)
Sum of each column of A: 		 tensor([3., 5., 7.])
Shape of A after summing each column: 	 torch.Size([3])

Sum of each column in A, w/o dimension reduction: 		 tensor([[3., 5., 7.]])
Shape of A after summing each column, w/o dimension reduction: 	 torch.Size([1, 3])



In [ ]:
A = torch.arange(12, dtype=torch.float32).reshape(4, 3)
print('Original matrix A: ')
print(A)
print()

print('Cumulative summation for each column')
print(A.cumsum(dim=0))
print()

print('Mean of elements in A (ver1): \t\t', A.mean())
print('Mean of elements in A (ver2): \t\t', A.sum()/A.numel())
print('Mean of elements in each column of A: \t', A.mean(dim=0))
print()

sum_A = A.sum(dim=1, keepdims=True)
print('Shape of A after summing each row, w/o dimension reduction: ')
print(sum_A)
print()

print('Division between A and sum_A by Broadcasting: ')
print(A/sum_A)

Original matrix A: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

Cumulative summation for each column
tensor([[ 0.,  1.,  2.],
        [ 3.,  5.,  7.],
        [ 9., 12., 15.],
        [18., 22., 26.]])

Mean of elements in A (ver1): 		 tensor(5.5000)
Mean of elements in A (ver2): 		 tensor(5.5000)
Mean of elements in each column of A: 	 tensor([4.5000, 5.5000, 6.5000])

Shape of A after summing each row, w/o dimension reduction: 
tensor([[ 3.],
        [12.],
        [21.],
        [30.]])

Division between A and sum_A by Broadcasting: 
tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167],
        [0.2857, 0.3333, 0.3810],
        [0.3000, 0.3333, 0.3667]])


In [ ]:
A = torch.arange(24).reshape(2, 3, 4)
print(A.shape)
# print(A)

sum_A = A.sum(dim=(0, 2), keepdims=True)
print(sum_A.shape)

print(A/sum_A)

torch.Size([2, 3, 4])
torch.Size([1, 3, 1])
tensor([[[0.0000, 0.0167, 0.0333, 0.0500],
         [0.0435, 0.0543, 0.0652, 0.0761],
         [0.0645, 0.0726, 0.0806, 0.0887]],

        [[0.2000, 0.2167, 0.2333, 0.2500],
         [0.1739, 0.1848, 0.1957, 0.2065],
         [0.1613, 0.1694, 0.1774, 0.1855]]])


### Multiplication with Matrix

In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
print('Original matrix A, with shape: ', A.shape)
print(A)
print()

B = torch.ones(3, 4)
print('Original matrix B, with shape: ', B.shape)
print(B)
print()

x = torch.arange(3, dtype=torch.float32)
print('Original Vector: \t', x)

Original matrix A, with shape:  torch.Size([2, 3])
tensor([[0., 1., 2.],
        [3., 4., 5.]])

Original matrix B, with shape:  torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Original Vector: 	 tensor([0., 1., 2.])


In [ ]:
print('Shape of matrix A: \t', A.shape)
print('Shape of vector x: \t', x.shape)
print('Result of Ax (ver1): \t', torch.mv(A, x), ' with shape ', torch.mv(A, x).shape)
print('Result of Ax (ver2): \t', (A@x), ' with shape ', (A@x).shape)
print()

print('Result of AB (ver1), with shape ', torch.mm(A, B).shape)
print(torch.mm(A, B))
print()

print('Result of AB (ver2), with shape ', (A@B).shape)
print(A@B)

Shape of matrix A: 	 torch.Size([2, 3])
Shape of vector x: 	 torch.Size([3])
Result of Ax (ver1): 	 tensor([ 5., 14.])  with shape  torch.Size([2])
Result of Ax (ver2): 	 tensor([ 5., 14.])  with shape  torch.Size([2])

Result of AB (ver1), with shape  torch.Size([2, 4])
tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

Result of AB (ver2), with shape  torch.Size([2, 4])
tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])


In [ ]:
batch_size = 64
w = 10
h = 5
l = 7

A = torch.rand(batch_size, w, h)
B = torch.rand(batch_size, h, l)

result = torch.bmm(A, B)
print(result.shape)

torch.Size([64, 10, 7])


### Tensor
A generic way of describing extensions to $n$-th order arrays.

In [ ]:
B = torch.arange(24).reshape(2, 3, 4)
print('Original Tensor B, with shape: ', B.shape)
print(B)

Original Tensor B, with shape:  torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


### Basic Properties of Tensor Arithmetic

#### Cloning the Tensor

In [ ]:
import copy

A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
# B = A.clone() # make copy of A by assigning new memory to B
B = copy.deepcopy(A)
print('Original Matrix A:')
print(A)
print()

print('Matrix 2*A: ')
print(A+B)
print()

print('Matrix A.*A (element-wise multiplication): ')
print(A*B)

Original Matrix A:
tensor([[0., 1., 2.],
        [3., 4., 5.]])

Matrix 2*A: 
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

Matrix A.*A (element-wise multiplication): 
tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])


### Adding the constant

In [ ]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)

print('Result of adding constant a to Tensor X, with shape: ', (a+X).shape)
print(a+X)

Result of adding constant a to Tensor X, with shape:  torch.Size([2, 3, 4])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])


### Norms
$l_p$ norm of vector $\mathbf{x}$: $\|\mathbf{x}\|_p = \Big( \sum_{i=1}^n |x_i|^p\Big)^{1/p}$

Frobenius norm for matrix $\mathbf{X}$: $\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}$

In [ ]:
u = torch.tensor([3.0, -4.0])
print('Original vector u: \t\t', u)
print('l2(Euclidean) norm of u: \t', torch.norm(u))
print('l1 norm of u (ver1): \t\t', torch.abs(u).sum())
print('l1 norm of u (ver2): \t\t', torch.norm(u, p=1))

A = torch.ones(4, 9)
print('Original Matrix A:')
print(A)
print('Frobenius Norm of A: ', torch.norm(A))

Original vector u: 		 tensor([ 3., -4.])
l2(Euclidean) norm of u: 	 tensor(5.)
l1 norm of u (ver1): 		 tensor(7.)
l1 norm of u (ver2): 		 tensor(7.)
Original Matrix A:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
Frobenius Norm of A:  tensor(6.)
